{
  "mitigation": "For users who are not able to update Requests immediately, there is one potential workaround.\nYou may disable redirects by setting allow_redirects to False on all calls through Requests top-level APIs. Note that if you are currently relying on redirect behaviors, you will need to capture the 3xx response codes and ensure a new request is made to the redirect destination.\nimport requests\nr = requests.get('http://github.com/', allow_redirects=False)",
  "affected_release": [
    {
      "product_name": "Red Hat Ansible Automation Platform 2.4 for RHEL 8",
      "release_date": "2023-08-21T00:00:00Z",
      "advisory": "RHSA-2023:4693",
      "package": "python3x-requests-0:2.31.0-1.el8ap",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2.4::el8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-11-14T00:00:00Z",
      "advisory": "RHSA-2023:7034",
      "package": "python39:3.9-8090020230922213827.7484f1d1",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-11-14T00:00:00Z",
      "advisory": "RHSA-2023:7034",
      "package": "python39-devel:3.9-8090020230922213827.7484f1d1",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-11-14T00:00:00Z",
      "advisory": "RHSA-2023:7042",
      "package": "python27:2.7-8090020231003120724.449e760b",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-11-14T00:00:00Z",
      "advisory": "RHSA-2023:7050",
      "package": "python38:3.8-8090020230810143931.d9f72c26",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-11-14T00:00:00Z",
      "advisory": "RHSA-2023:7050",
      "package": "python38-devel:3.8-8090020230810143931.d9f72c26",
      "cpe": "cpe:/a:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "release_date": "2023-08-08T00:00:00Z",
      "advisory": "RHSA-2023:4520",
      "package": "python-requests-0:2.20.0-3.el8_8",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8.6 Extended Update Support",
      "release_date": "2024-01-18T00:00:00Z",
      "advisory": "RHSA-2024:0299",
      "package": "python-requests-0:2.20.0-3.el8_6",
      "cpe": "cpe:/o:redhat:rhel_eus:8.6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "release_date": "2023-08-01T00:00:00Z",
      "advisory": "RHSA-2023:4350",
      "package": "python-requests-0:2.25.1-7.el9_2",
      "cpe": "cpe:/a:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "release_date": "2023-08-01T00:00:00Z",
      "advisory": "RHSA-2023:4350",
      "package": "python-requests-0:2.25.1-7.el9_2",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Satellite 6.14 for RHEL 8",
      "release_date": "2023-11-08T00:00:00Z",
      "advisory": "RHSA-2023:6818",
      "package": "python-requests-0:2.31.0-1.el8pc",
      "cpe": "cpe:/a:redhat:satellite:6.14::el8"
    },
    {
      "product_name": "Red Hat Satellite 6.14 for RHEL 8",
      "release_date": "2023-11-08T00:00:00Z",
      "advisory": "RHSA-2023:6818",
      "package": "python-requests-0:2.31.0-1.el8pc",
      "cpe": "cpe:/a:redhat:satellite_capsule:6.14::el8"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux 7",
      "release_date": "2023-11-08T00:00:00Z",
      "advisory": "RHSA-2023:6793",
      "package": "rh-python38-python-requests-0:2.22.0-11.el7",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3::el7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 1.2",
      "fix_state": "Affected",
      "package_name": "python-requests",
      "cpe": "cpe:/a:redhat:ansible_automation_platform"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "python-requests",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-requests",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 3.11",
      "fix_state": "Out of support scope",
      "package_name": "python-requests",
      "cpe": "cpe:/a:redhat:openshift:3.11"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Out of support scope",
      "package_name": "python-requests",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Affected",
      "package_name": "python-requests",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-05-23T00:00:00Z",
  "bugzilla": {
    "description": "python-requests: Unintended leak of Proxy-Authorization header",
    "id": "2209469",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2209469"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.1",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-402",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-32681",
  "document_distribution": "",
  "details": [
    "Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.",
    "A flaw was found in the Python-requests package, where it is vulnerable to potentially leaking Proxy-Authorization headers to destination servers, specifically during redirects to an HTTPS origin. This is a product of how rebuild_proxies is used to recompute and reattach the Proxy-Authorization header to requests when redirected. This behavior only affects proxied requests when credentials are supplied in the URL user information component (for example, https://username:password@proxy:8080)."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-32681\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-32681\nhttps://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"
  ]
}