{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ceph Storage 5",
      "fix_state": "Affected",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/a:redhat:ceph_storage:5"
    },
    {
      "product_name": "Red Hat Ceph Storage 6",
      "fix_state": "Affected",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/a:redhat:ceph_storage:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4",
      "fix_state": "Affected",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/a:redhat:openshift:4"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Will not fix",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "fix_state": "Will not fix",
      "package_name": "openstack-designate",
      "cpe": "cpe:/a:redhat:openstack:16.2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "fix_state": "Affected",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/a:redhat:openstack:16.2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.1",
      "fix_state": "Affected",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/a:redhat:openstack:17.1"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "quay/quay-rhel8",
      "cpe": "cpe:/a:redhat:quay:3"
    },
    {
      "product_name": "Red Hat Storage 3",
      "fix_state": "Affected",
      "package_name": "python-werkzeug",
      "cpe": "cpe:/a:redhat:storage:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-10-25T00:00:00Z",
  "bugzilla": {
    "description": "python-werkzeug: high resource consumption leading to denial of service",
    "id": "2246310",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2246310"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-407",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-46136",
  "document_distribution": "",
  "details": [
    "Werkzeug is a comprehensive WSGI web application library. If an upload of a file that starts with CR or LF and then is followed by megabytes of data without these characters: all of these bytes are appended chunk by chunk into internal bytearray and lookup for boundary is performed on growing buffer. This allows an attacker to cause a denial of service by sending crafted multipart data to an endpoint that will parse it. The amount of CPU time required can block worker processes from handling legitimate requests. This vulnerability has been patched in version 3.0.1.",
    "A resource consumption flaw was found in python-werkzeug. If a specially crafted file is uploaded by a remote attacker, it may cause a denial of service."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-46136\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-46136\nhttps://github.com/pallets/werkzeug/commit/f3c803b3ade485a45f12b6d6617595350c0f03e2\nhttps://github.com/pallets/werkzeug/security/advisories/GHSA-hrfv-mqp8-q5rw"
  ]
}