{
  "mitigation": "Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False`, disable automatic redirects with `redirects=False`, and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.",
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 1.2",
      "fix_state": "Under investigation",
      "package_name": "ansible-tower",
      "cpe": "cpe:/a:redhat:ansible_automation_platform"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "ansible-lint",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "ansible-navigator",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "automation-controller",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python3x-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python3x-pip",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python-ansible-compat",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Not affected",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "rhcertification/redhat-certification-baremetal",
      "cpe": "cpe:/a:redhat:certifications:1::el8"
    },
    {
      "product_name": "Red Hat Discovery",
      "fix_state": "Affected",
      "package_name": "discovery/discovery-server-rhel8",
      "cpe": "cpe:/a:redhat:discovery:1.0::el8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "python-urllib3",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-s3transfer",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-urllib3",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "resource-agents",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "container-tools:rhel8/python-podman",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "fence-agents",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "gimp:flatpak/python2-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "inkscape:flatpak/python2-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python27:2.7/python2-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python3.11-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python39:3.9/python3x-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Under investigation",
      "package_name": "python-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "python-urllib3",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "fence-agents",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "python3.11-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Under investigation",
      "package_name": "python-pip",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "python-urllib3",
      "cpe": "cpe:/o:redhat:enterprise_linux:9"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 3.11",
      "fix_state": "Under investigation",
      "package_name": "openvswitch-ovn-kubernetes",
      "cpe": "cpe:/a:redhat:openshift:3.11"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 3.11",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:openshift:3.11"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4",
      "fix_state": "Under investigation",
      "package_name": "openshift4/baremetal-hardware-event-proxy-rhel8",
      "cpe": "cpe:/a:redhat:openshift:4"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4",
      "fix_state": "Under investigation",
      "package_name": "openshift4/ztp-site-generate-rhel8",
      "cpe": "cpe:/a:redhat:openshift:4"
    },
    {
      "product_name": "Red Hat OpenShift Container Platform 4",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:openshift:4"
    },
    {
      "product_name": "Red Hat OpenShift Data Science (RHODS)",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:openshift_data_science"
    },
    {
      "product_name": "Red Hat OpenShift Data Science (RHODS)",
      "fix_state": "Under investigation",
      "package_name": "rhods/odh-ml-pipelines-api-server-rhel8",
      "cpe": "cpe:/a:redhat:openshift_data_science"
    },
    {
      "product_name": "Red Hat OpenShift Data Science (RHODS)",
      "fix_state": "Under investigation",
      "package_name": "rhods/odh-ml-pipelines-artifact-manager-rhel8",
      "cpe": "cpe:/a:redhat:openshift_data_science"
    },
    {
      "product_name": "Red Hat OpenShift Data Science (RHODS)",
      "fix_state": "Under investigation",
      "package_name": "rhods/odh-ml-pipelines-cache-rhel8",
      "cpe": "cpe:/a:redhat:openshift_data_science"
    },
    {
      "product_name": "Red Hat OpenShift Data Science (RHODS)",
      "fix_state": "Under investigation",
      "package_name": "rhods/odh-ml-pipelines-persistenceagent-rhel8",
      "cpe": "cpe:/a:redhat:openshift_data_science"
    },
    {
      "product_name": "Red Hat OpenShift Data Science (RHODS)",
      "fix_state": "Under investigation",
      "package_name": "rhods/odh-ml-pipelines-scheduledworkflow-rhel8",
      "cpe": "cpe:/a:redhat:openshift_data_science"
    },
    {
      "product_name": "Red Hat OpenShift Data Science (RHODS)",
      "fix_state": "Under investigation",
      "package_name": "rhods/odh-ml-pipelines-viewercontroller-rhel8",
      "cpe": "cpe:/a:redhat:openshift_data_science"
    },
    {
      "product_name": "Red Hat OpenStack Platform 10 (Newton)",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:openstack:10"
    },
    {
      "product_name": "Red Hat OpenStack Platform 13 (Queens)",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:openstack:13"
    },
    {
      "product_name": "Red Hat OpenStack Platform 15 (Stein)",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:openstack:15"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.1",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:openstack:17.1"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:quay:3"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Under investigation",
      "package_name": "quay/quay-rhel8",
      "cpe": "cpe:/a:redhat:quay:3"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Under investigation",
      "package_name": "ansiblerole-foreman_scap_client",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Affected",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Under investigation",
      "package_name": "satellite-capsule:el8/ansiblerole-foreman_scap_client",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Under investigation",
      "package_name": "satellite:el8/ansiblerole-foreman_scap_client",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Under investigation",
      "package_name": "rh-python38-python-pip",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Software Collections",
      "fix_state": "Will not fix",
      "package_name": "rh-python38-python-urllib3",
      "cpe": "cpe:/a:redhat:rhel_software_collections:3"
    },
    {
      "product_name": "Red Hat Storage 3",
      "fix_state": "Under investigation",
      "package_name": "graphite-web",
      "cpe": "cpe:/a:redhat:storage:3"
    },
    {
      "product_name": "Red Hat Storage 3",
      "fix_state": "Under investigation",
      "package_name": "python-urllib3",
      "cpe": "cpe:/a:redhat:storage:3"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-10-13T00:00:00Z",
  "bugzilla": {
    "description": "urllib3:  Request body not stripped after redirect from 303 status changes request method to GET",
    "id": "2246840",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2246840"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "4.2",
    "cvss3_scoring_vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-200",
  "statement": "Both of the following conditions must be true to be affected by this vulnerability: \n1. Using urllib3 and submitting sensitive information in the HTTP request body such as form data or JSON\n2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised",
  "acknowledgement": "",
  "name": "CVE-2023-45803",
  "document_distribution": "",
  "details": [
    "urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.",
    "A flaw was found in urllib3, an HTTP client library for Python. urllib3 doesn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303, after changing the method in a request from one that could accept a request body such as `POST` to `GET`, as is required by HTTP RFCs. This issue requires a previously trusted service to become compromised in order to have an impact on confidentiality, therefore, the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies; if this is the case, this vulnerability isn't exploitable."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-45803\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-45803\nhttps://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9\nhttps://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4\nhttps://www.rfc-editor.org/rfc/rfc9110.html#name-get"
  ]
}