{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 1.2",
      "fix_state": "Under investigation",
      "package_name": "aiohttp",
      "cpe": "cpe:/a:redhat:ansible_automation_platform"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 1.2",
      "fix_state": "Under investigation",
      "package_name": "python-aiohttp",
      "cpe": "cpe:/a:redhat:ansible_automation_platform"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "aiohttp",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Under investigation",
      "package_name": "python-aiohttp",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Under investigation",
      "package_name": "python-aiohttp",
      "cpe": "cpe:/a:redhat:satellite:6"
    },
    {
      "product_name": "Red Hat Update Infrastructure 4 for Cloud Providers",
      "fix_state": "Under investigation",
      "package_name": "python-aiohttp",
      "cpe": "cpe:/a:redhat:rhui:4::el8"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2023-11-29T00:00:00Z",
  "bugzilla": {
    "description": "aiohttp: CRLF injection if user controls the HTTP method using aiohttp client",
    "id": "2252248",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2252248"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.3",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "(CWE-20|CWE-93)",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2023-49082",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-49082\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-49082"
  ]
}