{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Ansible Automation Platform 1.2",
      "fix_state": "Affected",
      "package_name": "gitpython",
      "cpe": "cpe:/a:redhat:ansible_automation_platform"
    },
    {
      "product_name": "Red Hat Ansible Automation Platform 2",
      "fix_state": "Affected",
      "package_name": "automation-controller",
      "cpe": "cpe:/a:redhat:ansible_automation_platform:2"
    },
    {
      "product_name": "Red Hat Ansible Tower 3",
      "fix_state": "Affected",
      "package_name": "gitpython",
      "cpe": "cpe:/a:redhat:ansible_tower:3"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "redhat-certification-backend",
      "cpe": "cpe:/a:redhat:certifications:1::el6"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "redhat-certification",
      "cpe": "cpe:/a:redhat:certifications:1::el7"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 8",
      "fix_state": "Affected",
      "package_name": "redhat-certification",
      "cpe": "cpe:/a:redhat:certifications:1::el8"
    },
    {
      "product_name": "Red Hat Certification for Red Hat Enterprise Linux 9",
      "fix_state": "Affected",
      "package_name": "redhat-certification",
      "cpe": "cpe:/a:redhat:certifications:1::el9"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Will not fix",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "fix_state": "Will not fix",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:16.2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.0",
      "fix_state": "Will not fix",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:17.0"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.1",
      "fix_state": "Affected",
      "package_name": "GitPython",
      "cpe": "cpe:/a:redhat:openstack:17.1"
    },
    {
      "product_name": "Red Hat Satellite 6",
      "fix_state": "Affected",
      "package_name": "python-gitpython",
      "cpe": "cpe:/a:redhat:satellite:6"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-08-11T00:00:00Z",
  "bugzilla": {
    "description": "Insecure non-multi options in clone and clone_from is not blocked",
    "id": "2231474",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2231474"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "6.6",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-20",
  "statement": "This CVE is under investigation by Red Hat Product Security.",
  "acknowledgement": "",
  "name": "CVE-2023-40267",
  "document_distribution": "",
  "details": [
    "GitPython before 3.1.32 does not block insecure non-multi options in clone and clone_from. NOTE: this issue exists because of an incomplete fix for CVE-2022-24439."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2023-40267\nhttps://nvd.nist.gov/vuln/detail/CVE-2023-40267"
  ]
}