{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "release_date": "2023-10-10T00:00:00Z",
      "advisory": "RHSA-2023:5615",
      "package": "libssh2-0:1.8.0-4.el7_9.1",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Out of support scope",
      "package_name": "libssh2",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2023-08-22T00:00:00Z",
  "bugzilla": {
    "description": "libssh2: use-of-uninitialized-value in _libssh2_transport_read",
    "id": "2235542",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2235542"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "verified"
  },
  "iava": "",
  "cwe": "CWE-125",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2020-22218",
  "document_distribution": "",
  "details": [
    "An issue was discovered in function _libssh2_packet_add in libssh2 1.10.0 allows attackers to access out of bounds memory.",
    "A flaw was found in the libssh2 library. An out-of-bounds access issue can occur due to an improper initialization of a variable, resulting in a crash in the application linked to the library."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2020-22218\nhttps://nvd.nist.gov/vuln/detail/CVE-2020-22218"
  ]
}