{
  "mitigation": "Avoid leaving DEBUG log level enabled in critical environments.",
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat OpenStack Platform 16.1",
      "fix_state": "Out of support scope",
      "package_name": "python-glance-store",
      "cpe": "cpe:/a:redhat:openstack:16.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 16.2",
      "fix_state": "Out of support scope",
      "package_name": "python-glance-store",
      "cpe": "cpe:/a:redhat:openstack:16.2"
    },
    {
      "product_name": "Red Hat OpenStack Platform 17.1",
      "fix_state": "Affected",
      "package_name": "python-glance-store",
      "cpe": "cpe:/a:redhat:openstack:17.1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2024-01-17T00:00:00Z",
  "bugzilla": {
    "description": "glance-store: Glance Store access key logged in DEBUG log level",
    "id": "2258836",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2258836"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "5.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-779",
  "statement": "Red Hat rates this as a Moderate impact since DEBUG log level are normally not enabled in production environments and also, an attacker would need access to both changing the log level and read the log levels, would would imply the system is already compromised.",
  "acknowledgement": "Red Hat would like to thank Lujie (ICT) for reporting this issue.",
  "name": "CVE-2024-1141",
  "document_distribution": "",
  "details": [
    "No description is available for this CVE."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2024-1141\nhttps://nvd.nist.gov/vuln/detail/CVE-2024-1141"
  ]
}